### ISSUE TITLE
Fatal error: Cannot read property 'Compiler' of undefined

### ISSUE THREAD

**Issue by actionnick** [thlorenz/es6ify#17]
Added this to a package.json in a module I wrote (let's call it `my_project`) so that when I require it, the source will go through this transform.

```
"browserify": { "transform": [ "es6ify" ] }
```

However in a different JS project when I require this module I get this error...

```
Running "browserify:my_task" (browserify) task
Fatal error: Cannot read property 'Compiler' of undefined
TypeError: Cannot read property 'Compiler' of undefined
    at Object.<anonymous> (/my_project/node_modules/es6ify/compile.js:4:49)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/my_project/node_modules/es6ify/index.js:7:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

```

**Comment by thlorenz** [comment]
This should work now, please try again with latest es6ify.
