### ISSUE TITLE
Doesn't work with Browserify 2.20 + Node v0.10?

### ISSUE THREAD

**Issue by ryanwilliams** [thlorenz/es6ify#2]
Maybe I'm doing this wrong, but I can't get it to work at all. Here's what I have:

```
nvm install v0.10.12
npm install -g browserify
npm install es6ify
```

Andy I try to `browserify` it:

```
$ browserify -t es6ify foo.js -o bundle.js

/Users/Ryan/.nvm/v0.10.12/lib/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:91
                        var dir = path.resolve(x, pkg.main);
                                                     ^
TypeError: Cannot read property 'main' of undefined
    at /Users/Ryan/.nvm/v0.10.12/lib/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:91:54
    at load (/Users/Ryan/.nvm/v0.10.12/lib/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:54:43)
    at /Users/Ryan/.nvm/v0.10.12/lib/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:60:22
    at /Users/Ryan/.nvm/v0.10.12/lib/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:16:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by thlorenz** [comment]
This is an issue with the latest browserify inside the node-resolve dependency. I already encountered this myself and [raised an issue](https://github.com/substack/node-resolve/issues/22).
Please add your feedback there in order to track details about this problem.

In the meantime you could try to revert to an older 2.x version of browserify.
Thanks.

**Comment by thlorenz** [comment]
I assume this to be fixed now, so I'll close this.
