### ISSUE TITLE
docme generates a wierd error when run, even on Linux

### ISSUE THREAD

**Issue by domenic** [thlorenz/es6ify#59]
I thought this was a Windows problem, but I created a Linux VM and still had the problem. @thlorenz, help?

```
$ node_modules/.bin/docme README.md
info docme Updating API in "README.md" with current jsdocs

C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\node_modules\esprima\esprima.js:38
72
            throw e;
                  ^
Error: Line 1: Unexpected token >
    at throwError (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\node_modules\es
prima\esprima.js:1156:21)
    at throwUnexpected (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\node_modul
es\esprima\esprima.js:1213:9)
    at parsePrimaryExpression (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\nod
e_modules\esprima\esprima.js:1567:16)
    at C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\node_modules\esprima\esprim
a.js:3609:38
    at trackLeftHandSideExpressionAllowCall (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_mod
ules\jsdoc\node_modules\esprima\esprima.js:3504:61)
    at parsePostfixExpression (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\nod
e_modules\esprima\esprima.js:1703:20)
    at C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\node_modules\esprima\esprim
a.js:3609:38
    at parseUnaryExpression (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\node_
modules\esprima\esprima.js:1784:16)
    at C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\node_modules\esprima\esprim
a.js:3609:38
    at parseMultiplicativeExpression (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\js
doc\node_modules\esprima\esprima.js:1790:20)
ERR! docme Error: prog C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\jsdoc.js C:
\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify --destination C:\Users\Domenic\AppData\Local\Temp\es6ify\out --configure C
:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\config\jsdocrc.json returned with code 8
ERR! docme     at ChildProcess.<anonymous> (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\lib\run.j
s:45:17)
ERR! docme     at ChildProcess.emit (events.js:98:17)
ERR! docme     at maybeClose (child_process.js:756:16)
ERR! docme     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
ERR! docme  { [Error: prog C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\jsdoc.j
s C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify --destination C:\Users\Domenic\AppData\Local\Temp\es6ify\out --configu
re C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\config\jsdocrc.json returned with code 8
ERR! docme Details:
ERR! docme Error: prog C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\node_modules\jsdoc\jsdoc.js C:
\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify --destination C:\Users\Domenic\AppData\Local\Temp\es6ify\out --configure C
:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\config\jsdocrc.json returned with code 8
ERR! docme     at ChildProcess.<anonymous> (C:\Users\Domenic\Dropbox\GitHub\thlorenz\es6ify\node_modules\docme\lib\run.j
s:45:17)
ERR! docme     at ChildProcess.emit (events.js:98:17)
ERR! docme     at maybeClose (child_process.js:756:16)
ERR! docme     at Process.ChildProcess._handle.onexit (child_process.js:823:5)] stdout: '', code: 8 }
```

**Comment by thlorenz** [comment]
Yeah we need to add a `.jsdocrc` to prevent it from trying to parse everything.
The jsdoc guys don't pass the `nostrict` flag to esprima so it's very brittle.

I gave up trying to PR since they don't respond very well to those :(

So don't worry about the docs, just lmk when you need me to update them and I'll add the `.jsdocrc` and run docme.

**Comment by domenic** [comment]
I need you to update them :)

**Comment by thlorenz** [comment]
kk

**Comment by thlorenz** [comment]
ok done, all in `upgrade-traceur` branch.

Links won't work for now since they link to code in master. All will be fine once we merge this into master.

**Comment by domenic** [comment]
Sweet, merged. Sadly the environment-variable-setting in npm scripts doesn't work on Windows, but whatevs...

**Comment by thlorenz** [comment]
>  Sadly the environment-variable-setting in npm scripts doesn't work on Windows

Well you could always `set` it on the command line before running docme or just run docme while on the `master` branch.

**Comment by domenic** [comment]
Yeah it'd just be nice if `npm run docme` worked out of the box on all platforms.
