### ISSUE TITLE
Can't get source maps

### ISSUE THREAD

**Issue by skrat** [thlorenz/es6ify#8]
Having two files, foo.js (http://ix.io/7yY) and bar.js (http://ix.io/7yZ), and running:

```
./node_modules/browserify/bin/cmd.js -t es6ify -d -e bar.js
```

throws an error

```
;(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var Hello = require('./foo.js');
var instance = new Hello;
console.log(instance.greet());


},{"./foo.js":2}]
/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/array-set.js:83
    throw new Error('No element indexed by ' + aIdx);
          ^
Error: No element indexed by 1
    at ArraySet_at [as at] (/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/array-set.js:83:11)
    at SourceMapConsumer_parseMappings [as _parseMappings] (/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/source-map-consumer.js:158:44)
    at new SourceMapConsumer (/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/source-map-consumer.js:100:10)
    at module.exports (/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/lib/mappings-from-map.js:10:18)
    at Combiner._addExistingMap (/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:28:18)
    at Combiner.addFile (/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:58:12)
    at Stream.write (/home/skrat/Desktop/node_modules/browserify/node_modules/browser-pack/index.js:42:23)
    at Stream.stream.write (/home/skrat/Desktop/node_modules/browserify/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
```

Without `-d` everything works smooth.

**Comment by thlorenz** [comment]
Not using `-d` turns off browserify source maps, so I would guess the problem is there. More specifically inside combine-source-map or the source-map module that it uses.
Did this start happening recently and worked with previous browserify versions? If this is new, @ben-ng may know more since he was involved in making the recent switch to the source-map module.

Please try it via a build script as [indicated in the docs](https://github.com/thlorenz/es6ify#es6ify) as well to confirm that this happens either way.

**Comment by skrat** [comment]
Same error when using the build script, and sorry, no idea whether it's new as this is the first time I used es6ify.

**Comment by thlorenz** [comment]
Could you provide a failing test case or at least point me to an example so I can reproduce the error? By full example I mean a repo that I can clone instead of loose files. Thanks.

**Comment by skrat** [comment]
```
curl http://ix.io/7z4 | sh
```

**Comment by thlorenz** [comment]
Dude you just changed the link to some other file but I pushed it into a [proper repo](https://github.com/thlorenz/repro-sourcemap-issue) so others can have a look.

So just as an advice, please provide something similar to that repo next time which makes it much easier for people to look at your problem, instead of some curl script that runs without leaving me with any code to look at and stops working after 5 mins all together.

**Comment by thlorenz** [comment]
I tracked down the problem.
It was introduced with the latest version of combine-source-map. I rolled back that update.
After re-installing browserify everything is working again including your example.

Thanks for reporting this!
